# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Benchmark
on:
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
jobs:
    benchmark:
        runs-on: windows-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2.3.2
            - name: Set up .NET
              uses: actions/setup-dotnet@v1.6.0
              with:
                  dotnet-version: 5.0.100-preview.8.20417.9
            - name: Clone main repository
              run: |
                  git clone git://github.com/flare-lang/flare.git
            - name: Extract Git metadata
              id: metadata
              run: |
                  echo ::set-output name=sha::$(git -C flare show -s --format=%H)
                  echo ::set-output name=timestamp::$(git -C flare show -s --format=%ci)
                  echo ::set-output name=message::$(git -C flare show -s --format=%s)
                  echo ::set-output name=author_name::$(git -C flare show -s --format=%aN)
                  echo ::set-output name=author_email::$(git -C flare show -s --format=%aE)
                  echo ::set-output name=committer_name::$(git -C flare show -s --format=%cN)
                  echo ::set-output name=committer_email::$(git -C flare show -s --format=%cE)
            - name: Run benchmarks
              run: |
                  dotnet run -p flare/src/bench -c Release -- -j
            - name: Set Git identity
              run: |
                  git config --global user.name github-actions
                  git config --global user.email bot@flare-lang.org
            - name: Process benchmark results
              uses: alexrp/github-action-benchmark@flare
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  gh-pages-branch: live
                  name: Flare Programming Language
                  no-commit-event: true
                  commit-sha: ${{ steps.metadata.outputs.sha }}
                  commit-timestamp: ${{ steps.metadata.outputs.timestamp }}
                  commit-message: ${{ steps.metadata.outputs.message }}
                  commit-author-name: ${{ steps.metadata.outputs.author_name }}
                  commit-author-email: ${{ steps.metadata.outputs.author_email }}
                  commit-committer-name: ${{ steps.metadata.outputs.committer_name }}
                  commit-committer-email: ${{ steps.metadata.outputs.committer_email }}
                  commit-url: https://github.com/flare-lang/flare/commit/${{ steps.metadata.outputs.sha }}
                  tool: benchmarkdotnet
                  output-file-path: BenchmarkDotNet.Artifacts/results/Flare.Benchmarks.FlareBenchmark-report-full.json
                  benchmark-data-dir-path: ""
                  no-git-config: true
                  auto-push: true
