# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Benchmark
on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_NOLOGO: true
jobs:
    benchmark:
        runs-on: windows-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2.3.2
            - name: Fetch full history
              run: |
                  git fetch origin --unshallow
            - name: Set up .NET
              uses: actions/setup-dotnet@v1.6.0
              with:
                  dotnet-version: 5.0.100-preview.8.20417.9
            - name: Clone main repository
              run: |
                  git clone git://github.com/${{ github.repository_owner }}/flare.git
            - name: Run benchmarks
              run: |
                  dotnet run -p flare/src/bench -c Release -- -e
            - name: Update benchmark data
              id: update
              run: |
                  git config --global user.name github-actions
                  git config --global user.email bot@flare-lang.org
                  sha=$(git -C flare show -s --format=%H)
                  echo ::set-output name=sha::$sha
                  git checkout origin/live -b live
                  mv BenchmarkDotNet.Artifacts/results/Flare.Benchmarks.FlareBenchmark-report.json environment.json
                  echo ::set-output name=changed::$(git diff --quiet environment.json; echo $?)
                  jq --slurpfile data BenchmarkDotNet.Artifacts/results/Flare.Benchmarks.FlareBenchmark-report.json ". += \$data" reports.json > new.json
                  mv new.json reports.json
                  git add environment.json reports.json
                  git commit -m "CI: Benchmarks for $sha."
                  echo ::set-output name=result::$(git show -s --format=%H)
                  git push origin live
            - name: Notify Discord (environment)
              if: github.repository == 'flare-lang/flare-performance' && steps.update.outputs.changed == '1'
              uses: hugoalh/GitHubAction.SendToDiscord@v1.1.6
              with:
                  webhook_id: ${{ secrets.DISCORD_BENCHMARKS_ID }}
                  webhook_token: ${{ secrets.DISCORD_BENCHMARKS_TOKEN }}
                  message_embed_title: "Benchmarks: Environment"
                  message_embed_titleurl: https://github.com/${{ github.repository }}/commit/${{ steps.update.outputs.result }}
                  message_embed_description: The GitHub Actions environment appears to have changed. Benchmark history may need to be reset.
            - name: Notify Discord (completion)
              if: github.repository == 'flare-lang/flare-performance'
              uses: hugoalh/GitHubAction.SendToDiscord@v1.1.6
              with:
                  webhook_id: ${{ secrets.DISCORD_BENCHMARKS_ID }}
                  webhook_token: ${{ secrets.DISCORD_BENCHMARKS_TOKEN }}
                  message_embed_author: ${{ steps.update.outputs.sha }}
                  message_embed_authorurl: https://github.com/${{ github.repository_owner }}/flare/commit/${{ steps.update.outputs.sha }}
                  message_embed_title: "Benchmarks: Completed"
                  message_embed_titleurl: https://performance.flare-lang.org
                  message_embed_description: Benchmark run has completed successfully.
