# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI
on:
    push:
defaults:
    run:
        shell: bash
jobs:
    ci:
        runs-on: windows-latest
        steps:
            - uses: xt0rted/markdownlint-problem-matcher@v1
            - name: Clone repository
              uses: actions/checkout@v2.3.2
            - name: Set up Node.js
              uses: actions/setup-node@v1.4.3
            - name: Install dependencies
              run: |
                  npm install markdownlint-cli@0.23.2 -g
            - name: Lint Markdown files
              run: |
                  markdownlint *.md
            - name: Notify Discord
              if: failure() && github.event_name == 'push' && github.repository == 'flare-lang/flare-performance'
              uses: sarisia/actions-status-discord@v1.7.0
              with:
                  webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
