# Reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Reset
on:
    workflow_dispatch:
defaults:
    run:
        shell: bash
jobs:
    reset:
        runs-on: windows-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2.3.2
            - name: Fetch full history
              run: |
                  git fetch origin --unshallow
            - name: Reset history
              run: |
                  git config --global user.name github-actions
                  git config --global user.email bot@flare-lang.org
                  git checkout origin/live -b live
                  git reset $(git log --oneline --reverse --format=%H | head -n 1) --hard
                  git push origin live -f
